#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".js$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

printf "\nValidating Javascript\n"

$(npm bin)/eslint .
RESULT=$?
if [[ $RESULT != 0 ]]; then
  PASS=false
fi

printf "\nESLINT Validation Complete\n\n"

if ! $PASS; then
    printf "\033[31mCOMMIT FAILED:\033[0m Your commit contains files that failed ESLINT.\n"
    printf "Please fix the ESLINT errors and try to commit again.\n\n"
exit 1
fi

exit $?
