CREATE TABLE IF NOT EXISTS `notification` (`id` INTEGER UNSIGNED auto_increment , `notification` VARCHAR(255),
`isRead` TINYINT(1), `type` VARCHAR(255), `detail` VARCHAR(255), `createdAt` DATETIME NOT NULL,
`updatedAt` DATETIME NOT NULL, `subject` INTEGER UNSIGNED, PRIMARY KEY (`id`),
FOREIGN KEY (`subject`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `message` (`id` INTEGER UNSIGNED auto_increment , `title` VARCHAR(255), `detail` VARCHAR(255),
`isRead` TINYINT(1), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `fromId` INTEGER UNSIGNED,
`toId` INTEGER UNSIGNED, `parentId` INTEGER UNSIGNED, PRIMARY KEY (`id`),
FOREIGN KEY (`fromId`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY (`toId`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY (`parentId`) REFERENCES `message` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `work_experience` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `role` VARCHAR(255) NULL,
  `from` DATETIME NULL,
  `to` DATETIME NULL,
  `userId`  INTEGER UNSIGNED,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`userId`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `skill` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`)) ENGINE=InnoDB COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_skill` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userId` INT UNSIGNED,
  `skillId` INT UNSIGNED,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`userId`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (`skillId`)
    REFERENCES `skill` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `postv1_reply_rating` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rating` FLOAT,
  `userId` INT UNSIGNED,
  `replyId` INT UNSIGNED,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`userId`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (`replyId`)
    REFERENCES `reply` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `campus_user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `userId` INT(10) UNSIGNED,
  `campusId` INT(10) UNSIGNED,
  `campusEmail` VARCHAR(45) NULL,
  `token` VARCHAR(45) NULL,
  `emailVerified` TINYINT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`userId`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (`campusId`)
    REFERENCES `campus` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB COLLATE utf8_unicode_ci;
