CREATE TABLE IF NOT EXISTS `notification` (`id` INTEGER UNSIGNED auto_increment , `notification` VARCHAR(255),
`isRead` TINYINT(1), `type` VARCHAR(255), `detail` VARCHAR(255), `createdAt` DATETIME NOT NULL,
`updatedAt` DATETIME NOT NULL, `subject` INTEGER UNSIGNED, PRIMARY KEY (`id`),
FOREIGN KEY (`subject`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `message` (`id` INTEGER UNSIGNED auto_increment , `title` VARCHAR(255), `detail` VARCHAR(255),
`isRead` TINYINT(1), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `fromId` INTEGER UNSIGNED,
`toId` INTEGER UNSIGNED, `parentId` INTEGER UNSIGNED, PRIMARY KEY (`id`),
FOREIGN KEY (`fromId`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY (`toId`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY (`parentId`) REFERENCES `message` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB COLLATE utf8_unicode_ci;

